# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: address.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'address.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\raddress.proto\x12\x07\x61\x64\x64ress\"\x1e\n\x0bUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"U\n\x07\x41\x64\x64ress\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\x0c\n\x04\x63ity\x18\x03 \x01(\t\x12\r\n\x05state\x18\x04 \x01(\t\x12\x10\n\x08zip_code\x18\x05 \x01(\t\"2\n\x0b\x41\x64\x64ressList\x12#\n\taddresses\x18\x01 \x03(\x0b\x32\x10.address.Address2P\n\x0e\x41\x64\x64ressService\x12>\n\x10GetUserAddresses\x12\x14.address.UserRequest\x1a\x14.address.AddressListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'address_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_USERREQUEST']._serialized_start=26
  _globals['_USERREQUEST']._serialized_end=56
  _globals['_ADDRESS']._serialized_start=58
  _globals['_ADDRESS']._serialized_end=143
  _globals['_ADDRESSLIST']._serialized_start=145
  _globals['_ADDRESSLIST']._serialized_end=195
  _globals['_ADDRESSSERVICE']._serialized_start=197
  _globals['_ADDRESSSERVICE']._serialized_end=277
# @@protoc_insertion_point(module_scope)
